debug:
  registration:
    publish_clouds: true
    publish_clouds_alt: false

  stereo:
    print_stats: true
    publish_stats: true
    publish_intermediate_results: true
    publish_points: false
    rich_keypoints: false
    rich_matches: false
