# Remove first pointcloud
first_pointcloud_removal:
  enabled: true

# Filter to remove points with a time field value above a threshold
time_field_filter:
  enabled: true
  max: 0.1          # seconds

# Remove points within body region
body_filter:
  enabled: false
  min:
    x: 0.0
    y: 0.0
    z: 0.0
  max:
    x: 0.0
    y: 0.0
    z: 0.0
  translation:
    x: 0.0
    y: 0.0
    z: 0.0
  rotation:
    rx: 0.0
    ry: 0.0
    rz: 0.0

random_sample_filter:
  enabled: false
  sample_size: 5000
  random_seed: 0

range_filter:
  enabled: true
  min: 0.5
  max: 1000

# Remove points further than mean + stddev_mul_thresh * stddev where mean_k points are used for mean distance estimation
statistical_outlier_removal:
  enabled: false
  mean_k: 1
  stddev_mul_thresh: 0.0

# Downsample points into cubic voxels of side length equal to leaf_size if at least the minimum points are present
voxel_grid_filter:
  enabled: true
  leaf_size: 0.25
  minimum_points_number_per_voxel: 1

# Mask to apply to stereo images for feature extraction, with a coordinate system origin at the top left corner
stereo_mask:
  enabled: true
  top_left_x: 0
  top_left_y: 360
  height: 316
  width: 1577
