distortion_model: "plumb_bob"
distortion_coefficients: []

K: &K
  fx: 600
  fy: 400
  cx: 480
  cy: 320

P:
  fx: 600
  fy: 400
  cx: 480
  cy: 320
  baseline: 0.1 # 0.0 for monocular camera and left camera of a stereo pair
