function aligned_trajectory = align_to_first_pose(ref_trajectory, ...
    trajectory)
    % Find gt transform at timestamp of first pose
    gt_index = 1;
    while ref_trajectory.timestamps(gt_index) < trajectory.timestamps(1)
        gt_index = gt_index + 1;
    end
    if ref_trajectory.timestamps(gt_index) == trajectory.timestamps(1)
        first_gt_T = pose_to_matrix(ref_trajectory.poses(gt_index));
    else
        [first_gt_position, first_gt_orientation] = ...
            interp_transform(ref_trajectory.timestamps(gt_index - 1), ...
            ref_trajectory.timestamps(gt_index), ...
            ref_trajectory.poses(gt_index - 1), ...
            ref_trajectory.poses(gt_index), ...
            trajectory.timestamps(1));
        first_gt_T = [quat2rotm(first_gt_orientation), ...
            first_gt_position'; 0 0 0 1];
    end

    % Align all poses
    aligned_trajectory = recompute_trajectory(trajectory, ...
        matrix_to_pose(first_gt_T));
end

