clc;
clear;
close all;
addpath(genpath('.'));

data_base_dir = join([getenv("HOME"), "/data/jpl/"], "");
data_source = "eels1/";

%% Plot Options
plot_opts = default_plot_opts();
% plot_opts.align_first_pose = true;
plot_opts.align_first_pose = false;
plot_opts.align_trajectories = true;
plot_opts.align_opt_params.gamma = 0.95;
plot_opts.save = true;
plot_opts.close_figures = false;

%% Athabasca 005 Configuration
config = struct;
config.gt = struct;
data_name = "athabasca_005";
config.gt.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
config.gt.filename = "locus_gt_odometry_bodyframe_20s_to_100s_2023-02-18-20-52-03.bag";
config.gt.topic = "/eels1/lo_frontend/odometry";
config.gt.accelerometer_bias = [0.0, 0.0, 0.0];
config.gt.gyroscope_bias = [0.0, 0.0, 0.0];
config.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
analysis_name = "feb_28";
config.filenames = ["locus_2023-02-18-21-10-10.bag", ...
    "serpent_constant_3deg3cm_nomdc_quarterspeed_2023-02-27-23-59-51.bag", ...
    "serpent_constant_1deg1cm_nomdc_quarterspeed_2023-02-28-00-18-42.bag", ...
    "serpent_constant_p1deg1mm_nomdc_quarterspeed_2023-02-27-23-41-08.bag", ...
    "serpent_constant_p01degp1mm_nomdc_quarterspeed_2023-02-27-23-50-32.bag", ...
    "serpent_lls_nomdc_quarterspeed_2023-02-28-00-11-30.bag", ...
    "serpent_censi_constant_nomdc_quarterspeed_2023-02-28-00-25-43.bag", ...
    "serpent_censi_range_nomdc_quarterspeed_2023-02-28-00-43-46.bag", ...
    "serpent_lls_nomdc_baro_quarterspeed_2023-02-28-02-05-45.bag", ...
    "serpent_censi_constant_nomdc_baro_quarterspeed_2023-02-28-02-18-36.bag", ...
    "serpent_censi_range_nomdc_baro_quarterspeed_2023-02-28-02-25-09.bag"];
config.names = ["locus", ...
    "serpent constant (3deg, 3cm)", ...
    "serpent constant (1deg, 1cm)", ...
    "serpent constant (0.1deg, 1mm)", ...
    "serpent constant (0.01deg, 0.1mm)", ...
    "serpent i.i.d. LLS", ...
    "serpent i.i.d. Censi", ...
    "serpent Range Censi", ...
    "serpent i.i.d. LLS w/ baro", ...
    "serpent i.i.d. Censi w/ baro", ...
    "serpent Range Censi w/ baro"];
config.odom_topics = ["/eels1/lo_frontend/odometry", ...
    repmat("/serpent/optimisation/odometry", 1, 10)];
config.reg_tf_topics = ["", "", ...
    repmat("/serpent/registration/transform", 1, 10)];
config.track_points_statistics_topics = ["", ...
    repmat("/serpent/stereo/track_points_with_distances/statistics", 1, 5)];
config.filepaths = config.data_dir + config.filenames;

plot_opts.save_dir = join([data_base_dir, "analysis/", data_source, ...
    data_name, "/", analysis_name, "/"], "");
plot_opts.time_bounds.filter = false;

%% Big Bear 009
config = struct;
config.gt = struct;
data_name = "big_bear_009";
config.gt.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
config.gt.filename = "locus_gt_odometry_bodyframe_25s_to_120s_2023-02-26-15-14-38.bag";
config.gt.topic = "/eels1/lo_frontend/odometry";
config.gt.accelerometer_bias = [0.0, 0.0, 0.0];
config.gt.gyroscope_bias = [0.0, 0.0, 0.0];
config.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
analysis_name = "big_bear_009_feb_26";
config.filenames = ["locus_2023-02-26-15-29-09.bag", ...
    "serpent_constant_3deg3cm_nomdc_quarterspeed_2023-02-27-21-57-04.bag", ...
    "serpent_lls_nomdc_quarterspeed_2023-02-27-22-09-06.bag", ...
    "serpent_censi_constant_nomdc_quarterspeed_2023-02-27-22-14-37.bag", ...
    "serpent_censi_range_nomdc_quarterspeed_2023-02-27-22-20-03.bag"];
config.names = ["locus", "serpent constant (3deg, 3cm)", ...
    "serpent i.i.d. LLS", "serpent i.i.d. Censi", "serpent Range Censi"];
config.odom_topics = ["/eels1/lo_frontend/odometry", ...
    repmat("/serpent/optimisation/odometry", 1, 6)];
config.reg_tf_topics = ["", ...
    repmat("/serpent/registration/transform", 1, 6)];
config.track_points_statistics_topics = ["", ...
    repmat("/serpent/stereo/track_points_with_distances/statistics", 1, 6)];
config.filepaths = config.data_dir + config.filenames;

plot_opts.save_dir = join([data_base_dir, "analysis/", data_source, ...
    data_name, "/", analysis_name, "/"], "");
plot_opts.time_bounds.filter = true;
plot_opts.time_bounds.start = 5;
plot_opts.time_bounds.duration = 65;

%% Athabasca Moulin 053
config = struct;
config.gt = struct;
data_name = "athabasca_053";
config.gt.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
config.gt.filename = "locus_gt_odometry_bodyframe_50s_to_260s_2023-02-25-17-02-06.bag";
config.gt.topic = "/eels1/lo_frontend/odometry";
config.gt.accelerometer_bias = [0.0, 0.0, 0.0];
config.gt.gyroscope_bias = [0.0, 0.0, 0.0];
config.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
analysis_name = "feb_28";
config.filenames = ["locus_2023-02-25-19-21-46.bag", ...
    "serpent_constant_3deg3cm_nomdc_quarterspeed_2023-02-28-13-56-17.bag", ...
    "serpent_constant_1deg1cm_nomdc_quarterspeed_2023-02-28-13-13-33.bag", ...
    "serpent_constant_p1deg1mm_nomdc_quarterspeed_2023-02-28-13-36-51.bag", ...
    "serpent_lls_nomdc_quarterspeed_2023-02-28-12-53-25.bag", ...
    "serpent_lls_nomdc_baro_quarterspeed_2023-02-28-03-22-13.bag", ...
    "serpent_censi_constant_nomdc_quarterspeed_2023-02-28-12-38-08.bag", ...
    "serpent_censi_constant_nomdc_baro_quarterspeed_2023-02-28-03-44-26.bag", ...
    "serpent_censi_range_nomdc_quarterspeed_2023-02-28-12-23-28.bag", ...
    "serpent_censi_range_nomdc_baro_quarterspeed_2023-02-28-04-12-06.bag"];
config.names = ["locus", "serpent constant (3deg, 3cm)", ...
    "serpent constant (1deg, 1cm)", "serpent constant (0.1deg, 0.1cm)", ...
    "serpent i.i.d. LLS", "serpent i.i.d. LLS w/ baro", ...
    "serpent i.i.d. Censi", "serpent i.i.d. Censi w/ baro", ...
    "serpent Range Censi", "serpent Range Censi w/ baro"];
config.odom_topics = ["/eels1/lo_frontend/odometry", ...
    repmat("/serpent/optimisation/odometry", 1, 10)];
config.reg_tf_topics = ["", ...
    repmat("/serpent/registration/transform", 1, 10)];
config.track_points_statistics_topics = ["", ...
    repmat("/serpent/stereo/track_points_with_distances/statistics", 1, 10)];
config.filepaths = config.data_dir + config.filenames;

plot_opts.save_dir = join([data_base_dir, "analysis/", data_source, ...
    data_name, "/", analysis_name, "/"], "");
plot_opts.time_bounds.filter = false;

%% Big Bear 010
config = struct;
config.gt = struct;
data_name = "big_bear_010";
config.gt.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
config.gt.filename = "locus_gt_odometry_bodyframe_20s_to_83s_2023-02-27-10-30-06.bag";
config.gt.topic = "/eels1/lo_frontend/odometry";
config.gt.accelerometer_bias = [0.0, 0.0, 0.0];
config.gt.gyroscope_bias = [0.0, 0.0, 0.0];
config.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
analysis_name = "feb_27";
config.filenames = ["locus_2023-02-27-10-37-42.bag", ...
    "serpent_constant_3deg3cm_nomdc_2023-02-27-10-58-01.bag", ...
    "serpent_constant_1deg1cm_nomdc_2023-02-27-10-54-18.bag", ...
    "serpent_constant_p1deg1mm_nomdc_2023-02-27-10-52-41.bag", ...
    "serpent_constant_p01degp1mm_nomdc_2023-02-27-11-00-33.bag", ...
    "serpent_lls_nomdc_2023-02-27-11-15-17.bag", ...
    "serpent_censi_constant_nomdc_2023-02-27-11-19-48.bag", ...
    "serpent_censi_range_nomdc_2023-02-27-11-23-07.bag", ...
    "serpent_constant_1deg1cm_nomdc_quarterspeed_2023-02-27-13-36-13.bag", ...
    "serpent_constant_3deg3cm_nomdc_quarterspeed_2023-02-27-21-43-46.bag", ...
    "serpent_lls_nomdc_quarterspeed_2023-02-27-11-40-28.bag", ...
    "serpent_censi_constant_nomdc_quarterspeed_2023-02-27-11-33-53.bag", ...
    "serpent_censi_range_nomdc_quarterspeed_2023-02-27-11-27-59.bag"];
config.names = ["locus", "serpent constant (3deg, 3cm)", ...
    "serpent constant (1deg, 1cm)", "serpent constant (0.1deg, 0.1cm)", ...
    "serpent constant (0.01deg, 0.01cm", "serpent i.i.d. LLS", ...
    "serpent i.i.d. Censi", "serpent Range Censi", ...
    "serpent constant (1deg, 1cm) (1/4 speed)", ...
    "serpent constant (3deg, 3cm) (1/4 speed)", ...
    "serpent i.i.d. LLS (1/4 speed)", ...
    "serpent i.i.d. Censi (1/4 speed)", "serpent Range Censi (1/4 speed)"];
config.odom_topics = ["/eels1/lo_frontend/odometry", ...
    repmat("/serpent/optimisation/odometry", 1, 12)];
config.reg_tf_topics = ["", ...
    repmat("/serpent/registration/transform", 1, 12)];
config.track_points_statistics_topics = ["", ...
    repmat("/serpent/stereo/track_points_with_distances/statistics", 1, 12)];
config.filepaths = config.data_dir + config.filenames;

plot_opts.save_dir = join([data_base_dir, "analysis/", data_source, ...
    data_name, "/", analysis_name, "/"], "");
plot_opts.time_bounds.filter = false;

%% Athabasca 026
config = struct;
config.gt = struct;
data_name = "athabasca_026";
config.gt.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
config.gt.filename = "locus_gt_odometry_bodyframe_0s_to_540s_2023-02-28-17-41-18.bag";
config.gt.topic = "/eels1/lo_frontend/odometry";
config.gt.accelerometer_bias = [0.0, 0.0, 0.0];
config.gt.gyroscope_bias = [0.0, 0.0, 0.0];
config.data_dir = join([data_base_dir, "results/", data_source, ...
    data_name, "/"], "");
analysis_name = "feb_28";
config.filenames = [...
    "serpent_constant_p1deg1mm_nomdc_2023-03-01-20-51-14.bag", ...
    "serpent_constant_1deg1cm_nomdc_2023-02-28-17-20-36.bag", ...
    "serpent_lls_nomdc_2023-02-28-15-39-26.bag", ...
    "serpent_censi_constant_nomdc_2023-02-28-15-49-44.bag", ...
    "serpent_censi_range_nomdc_2023-02-28-15-59-51.bag", ...
    "serpent_lls_nomdc_quarterspeed_2023-02-28-20-07-07.bag", ...
    "serpent_censi_constant_nomdc_quarterspeed_2023-02-28-19-19-01.bag", ...
    "serpent_censi_range_nomdc_quarterspeed_2023-02-28-18-17-06.bag",...
    "serpent_constant_p1deg1mm_nomdc_rp15_2023-03-01-01-34-18.bag", ...
    "serpent_lls_nomdc_rp15_2023-03-01-00-21-06.bag",...
    "serpent_constant_lls_nomdc_rp15_2023-03-01-11-08-53.bag", ...
    "serpent_censi_constant_nomdc_rp15_2023-02-28-22-31-01.bag",...
    "serpent_censi_range_nomdc_rp15_2023-02-28-21-27-17.bag"];
config.names = ["serpent Constant (0.1deg, 1mm)", ...
    "serpent Constant (1deg, 1cm)", "serpent i.i.d. LLS", ...
    "serpent i.i.d. Censi", "serpent Range Censi", "serpent i.i.d. LLS (1/4)", ...
    "serpent i.i.d. Censi (1/4)", "serpent Range Censi (1/4)",...
    "serpent Constant (0.1deg, 1mm) (0.15)", ...
    "serpent i.i.d. LLS (0.15)", "serpent i.i.d. LLS 2 (0.15)", ...
    "serpent i.i.d. Censi (0.15)", "serpent Range Censi (0.15)"];
config.odom_topics = [... %["/eels1/lo_frontend/odometry", ...
    repmat("/serpent/optimisation/odometry", 1, 13)];
config.reg_tf_topics = [...
    repmat("/serpent/registration/transform", 1, 13)];
config.track_points_statistics_topics = [...
    repmat("/serpent/stereo/track_points_with_distances/statistics", 1, 13)];
config.filepaths = config.data_dir + config.filenames;

plot_opts.save_dir = join([data_base_dir, "analysis/", data_source, ...
    data_name, "/", analysis_name, "/"], "");
plot_opts.time_bounds.filter = false;
% plot_opts.time_bounds.start = 20;
% plot_opts.time_bounds.duration = 520;
plot_opts.align_opt_params.eta = 1.0e-6;
plot_opts.align_opt_params.iterations = 5000;
plot_opts.align_opt_params.gamma = 0.99;

%% Processing

% Odometry
odom_data = odom_data_from_rosbags(config);
[pose_data, twist_data] = plot_and_save(odom_data, plot_opts);

% Registration
try
    reg_transform_raw_data = raw_data_from_rosbags(config.filepaths, ...
        config.reg_tf_topics, "geometry_msgs/PoseWithCovarianceStamped");
    reg_transform_data = cell(length(config.filepaths), 1);
    for i = 1:length(config.filepaths)
        % Plot covariance over time
        reg_transform_data{i} = extract_pose_with_covariance_stamped(...
            reg_transform_raw_data{i});
        fig_cov = plot_pose_with_cov(reg_transform_data{i}, plot_opts);
        filename = join(["registration_covariance_", config.names(i)], "");
        save_and_close_figure(fig_cov, filename, plot_opts);

        % Plot translation error against normalised covariance
%         fig_cov_scatter = plot_normalised_covariance_scatter(...
%             pose_data.gt, pose_data.entries{i}, reg_transform_data{i});
    end
catch ex
    warning("Could not generate analysis for registration poses.");
end

% Stereo track points statistics
try
    track_points_statistics = raw_data_from_rosbags(config.filepaths, ...
        config.track_points_statistics_topics, ...
        "statistics_msgs/SummaryStatisticsArray");
    plot_summary_statistics(track_points_statistics, plot_opts);
%     track_points = raw_data_from_rosbags(config.filepaths, ...
%         config.track_points_topics, "sensor_msgs/PointCloud2");
%     plot_pointcloud_statistics(track_points, plot_opts);
catch ex
    warning(join([ ...
        "Could not generate analysis for track point statistics: ", ...
        ex.message], ""));
end

