debug:
  registration:
    publish_clouds: true
    publish_clouds_alt: false

  stereo:
    print_stats: true
    publish_stats: true
    publish_intermediate_results: true
    publish_points: false
    rich_keypoints: false
    rich_matches: false

  optimisation:
    publish_stereo_points: false
    on_crash:
      save: true
      print: true
      print_options:
        verbose: false
        min_error: 10.0
