debug:
  registration:
    check_normals: false
    publish_clouds: true
    publish_clouds_alt: false

  stereo:
    print_stats: true
    publish_stats: true
    publish_intermediate_results: true
    publish_points: true
    rich_keypoints: false
    rich_matches: false

  optimisation:
    publish_stereo_points: true
    on_crash:
      save: true
      print: true
      print_options:
        verbose: false
        min_error: 10.0
