debug:
  registration:
    publish_clouds: false
    publish_clouds_alt: false

  stereo:
    print_stats: false
    publish_stats: false
    publish_intermediate_results: false
    publish_points: false
    rich_keypoints: false
    rich_matches: false

  optimisation:
    publish_stereo_points: false
